# Generated by Django 5.0.6 on 2024-06-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='collection_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
